### ISSUE TITLE
是否可以将插件资产自动缓存到本地?

### ISSUE THREAD

**Issue by iceriny** [dynilath/Electron-BC#1]
服装拓展插件不能正确读取到资产~
插件: https://gitlab.com/Echo_87150/activity/-/raw/main/BC_Cloth2.user.js

有没有办法自动将额外的资产缓存到本地? 甚至包括BC版本更新是新添加的资产?

**Comment by dynilath** [comment]
目前的技术比较原始，仅仅是使用BC的git repo作为缓存编译到程序内。所以BC更新必须要更新程序。对BC的自动缓存我有考虑去实现。

这里提到的插件本身资产都是以`data:image/png;base64`编码在脚本里的，并且提供的user script总是加载最新版脚本，我认为这不是能缓存的。

**Comment by iceriny** [comment]
那有办法实现支持该插件么?这个插件目前用的人还蛮多的

**Comment by dynilath** [comment]
我暂时没有BC的环境，这个不支持的现象是什么，能提供一下网页控制台报错之类的信息吗？

**Comment by iceriny** [comment]
1. 无限弹出警告:

``` 
Layer.PoseMapping: Ignoring invalid "手臂空O_Luzi" pose
Array @ Pose.js:39
 Layer.PoseMapping: Ignoring invalid "手臂空Y_Luzi" pose
Array @ Pose.js:39
 Layer.PoseMapping: Ignoring invalid "手臂空D_Luzi" pose
Array @ Pose.js:39
```


2. 所拓展的服装和装置不在库存列表----参考服装(衣服栏位):`礼服` Or 装置(腿部两侧的身体栏位):`玻璃罐子`

**Comment by dynilath** [comment]
1. 这是BC本身的状态检查，这个物品本身制作得不符合BC的检查逻辑。
2. 额，2呢？
3. 这需要你有这两个物品，玻璃罐子是无法获得的，考虑使用全物品作弊代码。

**Comment by iceriny** [comment]
> 1. 这是BC本身的状态检查，这个物品本身制作得不符合BC的检查逻辑。

这个mod好像添加了一些新的pose?好像是添加的姿势不太对呢，Chrome上好像能够加载来着

> 2. 额，2呢？

咳...现在没有2了..

> 3. 这需要你有这两个物品，玻璃罐子是无法获得的，考虑使用全物品作弊代码。

这两个物品是这个插件新添的资产呢，不是BC原有的，总之没在库存中加载，但Chrome里就有

**Comment by dynilath** [comment]
跟这个插件的开发者沟通了一下，我目前认为是本地环境导致BC的脚本的加载速度远超插件脚本，导致的加载顺序问题。接下来我再催催他们。

**Comment by iceriny** [comment]
这个原因啊...你这个工具感觉十分有潜力! >.<  感谢感谢~
我只是个业余稍稍会点编程，不然也贡献代码了....再次感谢~

**Comment by emdsa2** [comment]
> 有办法实现支持该插件吗？这个插件目前用的人还蛮多的

可以了

**Comment by iceriny** [comment]
> > 有办法实现支持该插件吗？这个插件目前用的人还蛮多的
> 
> 可以了

似乎动作拓展还不行?

新增发现紧急问题(在不同人身上已复现):  制作物品无法使用，但在制作页面东西还在，只是无法使用.

**Comment by emdsa2** [comment]
> > > 有办法实现支持该插件吗？这个插件目前用的人还蛮多的
> > 
> > 
> > 可以了
> 
> 似乎行动尚未拓展？
> 
> 新增发现紧急问题（在不同的人身上已复现）：制作物品无法使用，但在制作页面物品仍然存在，只是无法使用。

修好了w，还增加了插件的图标显示在管理员盾牌下面

**Comment by iceriny** [comment]
> 修好了w，还增加了插件的图标显示在管理员盾牌下面

好耶! 辛苦啦!

**Comment by dynilath** [comment]
好耶！

**Comment by dynilath** [comment]
时隔一年 b21f2041ba49c0d7cf3f0709723a1c503ba26273 可以缓存了（
