### ISSUE TITLE
Cannot load FUSAM in latest version of Electron Bondage Club

### ISSUE THREAD

**Issue by Muhavaux33** [dynilath/Electron-BC#4]
In previous versions of the standalone bondage club version I was able to load FUSAM by loading the addon from an URL:
https://sidiousious.gitlab.io/bc-addon-loader/fusam.js

(https://sidiousious.gitlab.io/bc-addon-loader/)

But now I get a weird error and I can't get FUSAM to load:
![Screenshot 2024-09-06 225321](https://github.com/user-attachments/assets/e07df22d-cc79-461e-b76c-620eeb4f75aa)
![Untitled](https://github.com/user-attachments/assets/0c48eff5-8475-4471-828f-7bc2b5479e9e)

![image](https://github.com/user-attachments/assets/98cb7271-4bea-43c1-8b29-92a045848d56)

**Comment by dynilath** [comment]
I think the loader link for fusam should be https://sidiousious.gitlab.io/bc-addon-loader/loader.user.js

But the prompt here is not displayed correctly, which is an issue. I will fix it.
